site_name: Learn with Shashank
site_url: https://shashankshet.github.io/learn-with-shashank/
use_directory_urls: true
theme:
  name: material
nav:
  - Home: index.md
  - Developer Learning: developer_learning.md
  - Generic Software Engineering: generic_software_engineering.md
  - Miscellaneous: miscellaneous.md
